BEGIN

	UPDATE MARS_BTC110_TEMP 
		SET 
			SPE = CASE 
			WHEN UPPER(SPE) LIKE '%TIM%'
				OR UPPER(SPE) LIKE '%SPET%'
				OR UPPER(SPE) LIKE '%COZANI%'
				THEN 'TIM'
			WHEN UPPER(SPE) LIKE '%CLARO%'
				OR UPPER(SPE) LIKE '%SPEC%'
				OR UPPER(SPE) LIKE '%JONAVA%'
				THEN 'CLARO'
			WHEN UPPER(SPE) LIKE '%VIVO%'
				OR UPPER(SPE) LIKE '%SPEV%'
				OR UPPER(SPE) LIKE '%GARLIAVA%'
				THEN 'VIVO'
			ELSE 'NI'
			END
		WHERE UPPER(SPE) NOT IN ('TODOS','TODAS');

	INSERT INTO BIADHOC.TB_T_MARS_RESULTADO_IND_SLAS (
		NM_CODIGO_INDICADOR, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DT_DET_N3, DET_N4, DET_N5, ID_TIPO_RESULTADO)

    -----------------------
	-- INSERTs BTC110.1.1
	-----------------------
	
	SELECT NM_CODIGO_INDICADOR, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DT_DET_N3, DET_N4, DET_N5, ID_TIPO_RESULTADO FROM 
    (SELECT CONCAT(TB.CHAVE,'.1.1') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,TB.SPE
		,TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') AS DT_DET_N1
		,TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N2
		,TO_DATE(SUBSTR(TB.DT_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.AUDITORIA IS NULL
				THEN NULL
			ELSE CONCAT (
					'AUDITORIA '
					,TB.AUDITORIA
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.1')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.1') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        TB.SPE = JR.SPE AND
        TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N1 AND
		TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N2 AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('AUDITORIA ',TB.AUDITORIA) = JR.DET_N5) OR (TB.AUDITORIA IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DT_DET_N1 IS NULL AND
        JR.DT_DET_N2 IS NULL AND
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) NOT IN ('TODOS','TODAS')

    UNION ALL
    SELECT CONCAT (TB.CHAVE,'.1.1') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'TIM' AS SPE
		,TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') AS DT_DET_N1
		,TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N2
		,TO_DATE(SUBSTR(TB.DT_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.AUDITORIA IS NULL
				THEN NULL
			ELSE CONCAT (
					'AUDITORIA '
					,TB.AUDITORIA
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.1')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.1') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'TIM' = JR.SPE AND
        TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N1 AND
		TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N2 AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('AUDITORIA ',TB.AUDITORIA) = JR.DET_N5) OR (TB.AUDITORIA IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DT_DET_N1 IS NULL AND
        JR.DT_DET_N2 IS NULL AND
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')

    UNION ALL 
    SELECT CONCAT (TB.CHAVE,'.1.1') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'CLARO' AS SPE
		,TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') AS DT_DET_N1
		,TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N2
		,TO_DATE(SUBSTR(TB.DT_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN AUDITORIA IS NULL
				THEN NULL
			ELSE CONCAT (
					'AUDITORIA '
					,TB.AUDITORIA
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.1')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.1') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'CLARO' = JR.SPE AND
        TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N1 AND
		TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N2 AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('AUDITORIA ',TB.AUDITORIA) = JR.DET_N5) OR (TB.AUDITORIA IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DT_DET_N1 IS NULL AND
        JR.DT_DET_N2 IS NULL AND
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')

    UNION ALL 
    SELECT CONCAT (TB.CHAVE,'.1.1') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'VIVO' AS SPE
		,TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') AS DT_DET_N1
		,TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N2
		,TO_DATE(SUBSTR(TB.DT_ATENDIMENTO, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN AUDITORIA IS NULL
				THEN NULL
			ELSE CONCAT (
					'AUDITORIA '
					,TB.AUDITORIA
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DT_DET_N1, DT_DET_N2, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.1')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.1') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'VIVO' = JR.SPE AND
        TO_DATE(SUBSTR(TB.DT_SOLICITACAO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N1 AND
		TO_DATE(SUBSTR(TB.PRAZO_ATENDIMENTO, 1, 8), 'DD/MM/YY') = JR.DT_DET_N2 AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('AUDITORIA ',TB.AUDITORIA) = JR.DET_N5) OR (TB.AUDITORIA IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DT_DET_N1 IS NULL AND
        JR.DT_DET_N2 IS NULL AND
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')

    -----------------------
	-- INSERTs BTC110.1.2
	-----------------------

    UNION ALL
        SELECT CONCAT (TB.CHAVE,'.1.2') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,TB.SPE
		,NULL AS DT_DET_N1
		,NULL AS DT_DET_N2
		,TO_DATE(SUBSTR(TB.DT_EVIDENCIAS_CERTIFICADORA, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.CONTROLE IS NULL
				THEN NULL
			ELSE CONCAT (
					'CONTROLE '
					,TB.CONTROLE
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.2')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.2') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        TB.SPE = JR.SPE AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('CONTROLE ',TB.CONTROLE) = JR.DET_N5) OR (TB.CONTROLE IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) NOT IN ('TODOS','TODAS')

    UNION ALL
    SELECT CONCAT(TB.CHAVE,'.1.2') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'TIM' AS SPE
		,NULL AS DT_DET_N1
		,NULL AS DT_DET_N2
	    ,TO_DATE(SUBSTR(TB.DT_EVIDENCIAS_CERTIFICADORA, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.CONTROLE IS NULL
				THEN NULL
			ELSE CONCAT (
					'CONTROLE '
					,TB.CONTROLE
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.2')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.2') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'TIM' = JR.SPE AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('CONTROLE ',TB.CONTROLE) = JR.DET_N5) OR (TB.CONTROLE IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')

    UNION ALL 
    SELECT CONCAT (TB.CHAVE,'.1.2') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'CLARO' AS SPE
		,NULL AS DT_DET_N1
		,NULL AS DT_DET_N2
	    ,TO_DATE(SUBSTR(TB.DT_EVIDENCIAS_CERTIFICADORA, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.CONTROLE IS NULL
				THEN NULL
			ELSE CONCAT (
					'CONTROLE '
					,TB.CONTROLE
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.2')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.2') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'CLARO' = JR.SPE AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('CONTROLE ',TB.CONTROLE) = JR.DET_N5) OR (TB.CONTROLE IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')

    UNION ALL 
    SELECT CONCAT (TB.CHAVE,'.1.2') AS NM_CODIGO_INDICADOR
		,TO_DATE(SUBSTR(TB.MES_COMPETENCIA, 1, 8), 'DD/MM/YY') AS DT_DATA_RES
		,'VIVO' AS SPE
		,NULL AS DT_DET_N1
		,NULL AS DT_DET_N2
	    ,TO_DATE(SUBSTR(TB.DT_EVIDENCIAS_CERTIFICADORA, 1, 8), 'DD/MM/YY') AS DT_DET_N3
		,TB.PROCESSO_EQUIPE AS DET_N4
		,CASE 
			WHEN TB.CONTROLE IS NULL
				THEN NULL
			ELSE CONCAT (
					'CONTROLE '
					,TB.CONTROLE
					)
			END AS DET_N5
		,0 AS ID_TIPO_RESULTADO
	FROM MARS_BTC110_TEMP TB
    LEFT JOIN 
        (SELECT DISTINCT NM_CODIGO_INDICADOR AS CHAVE, DT_DATA_RES, SPE, DET_N4, DET_N5
        FROM TB_T_MARS_RESULTADO_IND_SLAS 
        WHERE NM_CODIGO_INDICADOR IN ('BTC110.1.2')) JR 
    ON 
        CONCAT(TB.CHAVE,'.1.2') = JR.CHAVE AND 
        TO_DATE(SUBSTR(TB.MES_COMPETENCIA,1,8),'DD/MM/YY') = JR.DT_DATA_RES AND 
        'VIVO' = JR.SPE AND
        TB.PROCESSO_EQUIPE = JR.DET_N4 AND
		((CONCAT('CONTROLE ',TB.CONTROLE) = JR.DET_N5) OR (TB.CONTROLE IS NULL AND JR.DET_N5 IS NULL))
    WHERE 
        JR.CHAVE IS NULL AND 
        JR.DT_DATA_RES IS NULL AND 
        JR.SPE IS NULL AND 
        JR.DET_N4 IS NULL AND
		JR.DET_N5 IS NULL
		AND UPPER(TB.SPE) IN ('TODOS','TODAS')) TB;

    -----------------------
    --- MERGE BTC110.1.1
    -----------------------

    MERGE 
    INTO TB_T_MARS_RESULTADO_IND_SLAS TB1
    USING (

        SELECT CONCAT(CHAVE,'.1.1') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) NOT IN ('TODOS','TODAS')

        UNION ALL
        SELECT CONCAT(CHAVE,'.1.1') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'CLARO' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')
        
        UNION ALL
        SELECT CONCAT(CHAVE,'.1.1') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'TIM' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')

        UNION ALL
        SELECT CONCAT(CHAVE,'.1.1') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'VIVO' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')

        ) TB2 ON (
            TB1.NM_CODIGO_INDICADOR = TB2.CHAVE AND
            TB1.DT_DATA_RES = TO_DATE(SUBSTR(TB2.MES_COMPETENCIA,1,8),'DD/MM/YY') AND
            TB1.SPE = TB2.SPE AND
            TB1.DT_DET_N1 = TO_DATE(SUBSTR(TB2.DT_SOLICITACAO,1,8),'DD/MM/YY') AND
            TB1.DT_DET_N2 = TO_DATE(SUBSTR(TB2.PRAZO_ATENDIMENTO,1,8),'DD/MM/YY') AND
            TB1.DET_N4 = TB2.PROCESSO_EQUIPE AND
            ((TB1.DET_N5 = CONCAT('AUDITORIA ',TB2.AUDITORIA)) OR (TB2.AUDITORIA IS NULL AND TB1.DET_N5 IS NULL)))
          
            
            WHEN MATCHED THEN UPDATE SET
                TB1.DT_DET_N3 = TO_DATE(SUBSTR(TB2.DT_ATENDIMENTO,1,8),'DD/MM/YY') 
                WHERE
                    TB1.NM_CODIGO_INDICADOR IN ('BTC110.1.1') AND
                    TB1.DT_DET_N3 IS NULL;
         

    -----------------------
    --- MERGE BTC110.1.2
    -----------------------

    MERGE 
    INTO TB_T_MARS_RESULTADO_IND_SLAS TB1
    USING (

        SELECT CONCAT(CHAVE,'.1.2') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) NOT IN ('TODOS','TODAS')

        UNION ALL
        SELECT CONCAT(CHAVE,'.1.2') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'CLARO' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')
        
        UNION ALL
        SELECT CONCAT(CHAVE,'.1.2') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'TIM' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')

        UNION ALL
        SELECT CONCAT(CHAVE,'.1.2') AS CHAVE, INDICADOR, MES, MES_COMPETENCIA, 'VIVO' AS SPE, CONTROLE, PROCESSO_EQUIPE, DT_EVIDENCIAS_CERTIFICADORA, 
        	AUDITORIA, DT_SOLICITACAO, PRAZO_ATENDIMENTO, DT_ATENDIMENTO 
        FROM MARS_BTC110_P3_TEMP  WHERE UPPER(SPE) IN ('TODOS','TODAS')

        ) TB2 ON (
            TB1.NM_CODIGO_INDICADOR = TB2.CHAVE AND
            TB1.DT_DATA_RES = TO_DATE(SUBSTR(TB2.MES_COMPETENCIA,1,8),'DD/MM/YY') AND
            TB1.SPE = TB2.SPE AND
            TB1.DET_N4 = TB2.PROCESSO_EQUIPE AND
            ((TB1.DET_N5 = CONCAT('CONTROLE ',TB2.CONTROLE)) OR (TB1.DET_N5 IS NULL AND TB2.CONTROLE IS NULL)))
            
            WHEN MATCHED THEN UPDATE SET
                TB1.DT_DET_N3 = TO_DATE(SUBSTR(TB2.DT_EVIDENCIAS_CERTIFICADORA,1,8),'DD/MM/YY') 
                WHERE
                    TB1.NM_CODIGO_INDICADOR IN ('BTC110.1.2') AND
                    TB1.DT_DET_N3 IS NULL;




END;

